services:
  influxdb:
    image: influxdb:2.1-alpine
    ports:
      - 8086:8086
    networks:
      - influx
    volumes:
      - influxdb2:/var/lib/influxdb2
      - influxconf:/etc/influxdb2

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    networks:
      - influx

volumes:
  influxdb2: {}
  influxconf: {}

networks:
  influx: {}
