#!/bin/pwsh
$stat1=$(Get-Content /proc/stat -First 1).Split(" ")
$fullcpu1=0
for ($i=2; $i -le $stat1.count; $i++){
    $fullcpu1=$fullcpu1+ [int]$stat1[$i]
}
sleep 1
$stat2=$(Get-Content /proc/stat -First 1).Split(" ")
$fullcpu2=0
for ($j=2; $j -le $stat2.count; $j++){
    $fullcpu2=$fullcpu2+ [int]$stat2[$j]
}
$delta=$fullcpu2-$fullcpu1
$idle=[int]$stat2[5]-[int]$stat1[5]

$usage=(1-($idle/$delta))*100
$usage=[math]::Round($usage, 2)
Write-Host -NoNewline "cpu,host=linux usage_percent=$usage $(get-date -UFormat %s)"
