#!/usr/bin/pwsh
$free=$(free -k | awk '/^Mem/ {print $7}')
$total=$(free -k | awk '/^Mem/ {print $2}')
$used_kbytes=$total-$free
$used_percent=($used_kbytes/$total)*100
$used_percent=[math]::Round($used_percent, 2)
Write-Host -NoNewline "memory,host=linux usage_percent=$used_percent,usage_kbytes=$used_kbytes $(get-date -UFormat %s)"