version: "3"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - influxdb

    influxdb:
        image: influxdb:1.8
        expose:
            - "8086"
        volumes:
            - ./influxdb:/var/lib/influxdb
